version: '3'
services:
  docker_php74:
    container_name: "docker_php74"
    build: ./
    volumes:
      - ./etc/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../src:/opt/project/src
      - ../tests:/opt/project/tests
      - ../phpunit.xml:/opt/project/phpunit.xml
    ports:
      - 10080:80
    networks:
      - sample-network
    tty: true

  mysql8_phptest:
    image: mysql:8
    container_name: mysql8_phptest
    volumes:
    - ./etc/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    restart: always
    ports:
      - 23306:3306
    networks:
      - sample-network
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_ROOT: root
      MYSQL_PASSWORD: user_pass
      MYSQL_ROOT_PASSWORD: root_pass

networks:
  sample-network:
    external:
      name: bridge
